In [3]:
import os
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [5]:
data_directory = os.path.join(os.getcwd(), 'dataset_diabetes')

In [7]:
diabetes = pd.read_csv(os.path.join(data_directory, 'diabetic_data.csv'))

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train_set, test_set = train_test_split(diabetes, test_size=0.2, random_state=42)

In [10]:
train_set.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
24079,81844290,94788,Caucasian,Female,[70-80),?,1,1,7,4,...,No,No,No,No,No,No,No,No,No,NO
98079,396159158,135023315,Caucasian,Male,[50-60),?,1,1,7,1,...,No,No,No,No,No,No,No,No,No,>30
6237,31258956,18397782,Caucasian,Male,[80-90),?,1,1,7,4,...,No,No,No,No,No,No,No,No,Yes,NO
72208,210691074,67509558,Caucasian,Male,[80-90),?,1,3,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
33075,104902980,23272362,AfricanAmerican,Female,[70-80),?,1,11,7,11,...,No,No,No,No,No,No,No,No,No,NO

In [13]:
train_set.shape

(81412, 50)

In [12]:
test_set.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
35956,110939484,19274094,Caucasian,Female,[70-80),?,1,1,6,11,...,No,Steady,No,No,No,No,No,No,Yes,NO
60927,170328306,65634327,Caucasian,Male,[50-60),?,1,1,1,1,...,No,No,No,No,No,No,No,No,Yes,NO
79920,245688426,100657359,Caucasian,Female,[60-70),?,3,6,1,4,...,No,No,No,No,No,No,No,No,Yes,NO
50078,150826224,83144448,Caucasian,Male,[30-40),?,2,1,1,12,...,No,No,No,No,No,No,No,No,Yes,>30
44080,135993852,65234214,AfricanAmerican,Female,[60-70),?,1,2,7,1,...,No,No,No,No,No,No,No,No,Yes,<30

In [15]:
test_set.shape

(20354, 50)

In [16]:
train_set.to_csv(os.path.join(data_directory, 'diabetic_data_train.csv'), index=False)

In [17]:
test_set.to_csv(os.path.join(data_directory, 'diabetic_data_test.csv'), index=False)

In [18]:
#checking if train and test data was saved properly
train_saved = pd.read_csv(os.path.join(data_directory, 'diabetic_data_train.csv'))

In [19]:
train_saved.shape

(81412, 50)

In [20]:
train_saved.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,81844290,94788,Caucasian,Female,[70-80),?,1,1,7,4,...,No,No,No,No,No,No,No,No,No,NO
1,396159158,135023315,Caucasian,Male,[50-60),?,1,1,7,1,...,No,No,No,No,No,No,No,No,No,>30
2,31258956,18397782,Caucasian,Male,[80-90),?,1,1,7,4,...,No,No,No,No,No,No,No,No,Yes,NO
3,210691074,67509558,Caucasian,Male,[80-90),?,1,3,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
4,104902980,23272362,AfricanAmerican,Female,[70-80),?,1,11,7,11,...,No,No,No,No,No,No,No,No,No,NO